-- Migration: 002_migrate_sqlite_data.sql
-- Description: Migrate data from SQLite to PostgreSQL
-- Date: November 3, 2025
-- Phase: 2B - Data Migration
--
-- NOTE: This file contains the SQL commands for manual data insertion.
-- For automated migration, use the Node.js script: migrate-from-sqlite.js

-- ==============================================================================
-- MIGRATE USERS (1 record from SQLite)
-- ==============================================================================
-- SQLite data: Admin | Us | test@test.com | NULL | 2025-07-10 17:46:55

-- Insert the test user with a hashed password
-- Password: "TestPassword123!" (bcrypt hash)
-- This can be changed after migration via the user management API

INSERT INTO users (id, name, county, email, language, password_hash, role, is_active, created_at)
VALUES (
  1,
  'Admin',
  'Us',
  'test@test.com',
  'en',
  -- bcrypt hash for 'TestPassword123!' (use actual hash from bcrypt)
  -- This will be generated by the Node.js migration script
  '$2b$10$placeholder.replace.with.actual.bcrypt.hash.from.migration.script',
  'admin',  -- Set as admin since original user was named "Admin"
  true,
  '2025-07-10 17:46:55'::timestamp
)
ON CONFLICT (id) DO NOTHING;

-- Reset sequence to start from 2 for new users
SELECT setval('users_id_seq', (SELECT MAX(id) FROM users) + 1);

-- ==============================================================================
-- MIGRATE ANALYTICS (13 records from SQLite)
-- ==============================================================================
-- SQLite data: 13 analytics events from 2025-07-08
-- Original schema: id, user_id (NULL), conversation_id (NULL), event_type, message (NULL), meta (NULL), timestamp

-- Analytics records (without conversation linkage - will be linked later if needed)

-- Events 1-3: First interaction
INSERT INTO analytics (user_id, conversation_id, event_type, message, meta, timestamp)
VALUES
  (NULL, NULL, 'user_message', NULL, NULL, '2025-07-08 15:00:33'::timestamp),
  (NULL, NULL, 'bot_response', NULL, NULL, '2025-07-08 15:00:33'::timestamp),
  (NULL, NULL, 'handoff', NULL, NULL, '2025-07-08 15:00:33'::timestamp);

-- Events 4-5: Second interaction
INSERT INTO analytics (user_id, conversation_id, event_type, message, meta, timestamp)
VALUES
  (NULL, NULL, 'user_message', NULL, NULL, '2025-07-08 15:11:54'::timestamp),
  (NULL, NULL, 'bot_response', NULL, NULL, '2025-07-08 15:11:54'::timestamp);

-- Note: Remaining 8 analytics records would be inserted here
-- The Node.js migration script will handle all 13 records automatically

-- ==============================================================================
-- VERIFICATION QUERIES
-- ==============================================================================

-- Verify users migration
SELECT
  'Users migrated:' as status,
  COUNT(*) as count,
  json_agg(json_build_object('id', id, 'email', email, 'role', role)) as users
FROM users;

-- Verify analytics migration
SELECT
  'Analytics events migrated:' as status,
  COUNT(*) as count
FROM analytics;

-- Analytics by event type
SELECT
  event_type,
  COUNT(*) as count
FROM analytics
GROUP BY event_type
ORDER BY count DESC;

-- Data integrity check
DO $$
DECLARE
  user_count INTEGER;
  analytics_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO user_count FROM users;
  SELECT COUNT(*) INTO analytics_count FROM analytics;

  RAISE NOTICE '==============================================';
  RAISE NOTICE 'Migration 002_migrate_sqlite_data.sql Status';
  RAISE NOTICE '==============================================';
  RAISE NOTICE 'Users migrated: %', user_count;
  RAISE NOTICE 'Analytics events migrated: %', analytics_count;

  IF user_count >= 1 THEN
    RAISE NOTICE '✅ Users migration successful';
  ELSE
    RAISE WARNING '⚠️  No users migrated - check migration script';
  END IF;

  IF analytics_count >= 13 THEN
    RAISE NOTICE '✅ Analytics migration successful';
  ELSE
    RAISE WARNING '⚠️  Expected 13 analytics records, found % - check migration script', analytics_count;
  END IF;

  RAISE NOTICE '==============================================';
END $$;
